### ISSUE TITLE
Broken in Home Assistant 0.98.5

### ISSUE THREAD

**Issue by cornubot** [o0Zz/ha-melcloud#19]
The component is broken in Home Assistant 0.98, at least version 0.98.5. Error from log file:

2019-09-12 10:38:01 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/Users/culture/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/entity_platform.py", line 300, in _async_add_entity
    if entity.unique_id is not None:
AttributeError: 'MelCloudClimate' object has no attribute 'unique_id'

**Comment by dolenec** [comment]
For me is working completly normally - using 3 melcloud adapters in HA..

**Comment by MuppetOwl** [comment]
Yes working on 0.98.5 without any issues. so its not broken. Have to be a local issue, or maybe a miss configuration.

**Comment by cornubot** [comment]
Thanks for the swift responses. As it does work for you, I downloaded and reinstalled, and it works now.
